version: '3.3'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/kafka:3.1.0-debian-10-r89
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - '2181:2181'
    networks:
      - custom-network

  kafka:
    image: 'bitnami/kafka:3.1.0-debian-10-r89'
    ports:
      - "5221:9092"
      - "5222:9093"
      - "5224:9094"
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=50VGJ_HYQiq3H2dD81JGTA
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - custom-network
  
  kafka-init:
    image: 'bitnami/kafka:3.1.0-debian-10-r89'
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server $$SERVER --list
      echo 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server $$SERVER --create --if-not-exists --topic $$TOPIC --replication-factor 1 --partitions 3
      echo 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server $$SERVER --list
      "
    environment:
      SERVER: 'kafka:9092'
      TOPIC: 'simple-connect'
    networks:
      - custom-network

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:7.0.3
    container_name: kafka-rest-proxy
    restart: always
    depends_on:
      - kafka
    ports:
      - "5324:8086"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_LISTENERS: http://0.0.0.0:8086
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:19092
    networks:
      - custom-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "5223:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - custom-network

  kinesis:
    image: "localstack/localstack:latest"
    container_name: kinesis
    environment:
      EDGE_PORT: 4566
      SERVICES: kinesis
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: FakeKey
      AWS_SECRET_ACCESS_KEY: FakeKey
      KINESIS_INITIALIZE_STREAMS: simple-sink-connect-stream:1,simple-source-connect-stream:1
    ports:
      - '4566-4583:4566-4583'
    depends_on:
      - kafka
    networks:
      - custom-network

  source-kinesis-connector:
    build:
      context: .
      dockerfile: distributed-source-connector/Dockerfile
    deploy:
      replicas: 3
    ports:
      - "8083"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - custom-network

  sink-kinesis-connector:
    build:
      context: .
      dockerfile: distributed-sink-connector/Dockerfile
    deploy:
      replicas: 3
    ports:
      - "8083"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - custom-network

  kinesis-consumer:
    build:
      context: ./kinesis-consumer
      dockerfile: Dockerfile
    container_name: kinesis-consumer
    depends_on:
      - kinesis
    networks:
      - custom-network

networks:
  custom-network:
    name: kinesis-poc
