$JSON = @{
"name"= "kinesis-sink-connector"
"connector.class"= "com.amazon.kinesis.kafka.AmazonKinesisSinkConnector"
"tasks.max"= "1"
"topics"= "simple-connect"
"region"= "us-west-1"
"streamName"= "simple-connect-stream"
"usePartitionAsHashKey"= "false"
"flushSync"= "true"
"singleKinesisProducerPerPartition"= "true"
"pauseConsumption"= "true"
"outstandingRecordsThreshold"= "500000"
"sleepPeriod"= "1000"
"sleepCycles"= "10"
"maxBufferedTime"= "1500"
"maxConnections"= "1"
"rateLimit"= "100"
"ttl"= "60000"
"metricsLevel"= "detailed"
"metricsGranuality"= "shard"
"metricsNameSpace"= "KafkaKinesisStreamsConnector"
"aggregation"= "true"
}

Invoke-WebRequest -Uri http://localhost:8084/connectors/file-sink-connector/config -Method PUt -Body ($JSON|ConvertTo-Json) -ContentType "application/json"